version: "3.8"
services:
  kroki:
    image: yuzutech/kroki
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
  # experimental!
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    expose:
      - "8005"
  
  mermaid-ink:
    image: ghcr.io/jihchi/mermaid.ink
    ports:
      - 4000:3000
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_OPTIONS=--max-http-header-size=102400000

  mermaid-live:
    build:
      context: ./mermaid-live-editor
      target: mermaid-dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      MERMAID_RENDERER_URL: "http://localhost:4000"
      MERMAID_KROKI_RENDERER_URL: "http://localhost:8002"


  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - mermaid-ink
      - kroki
    environment:
      MERMAID_RENDERER_URL: "http://localhost:4000"
      MERMAID_KROKI_RENDERER_URL: "http://localhost:8002"
  